# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_auto_20170321_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='secret',
            name='users',
            field=models.ManyToManyField(related_name='likes', to='secrets.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
