# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_auto_20170321_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='users',
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='user', to='secrets.User'),
        ),
    ]
